services:
  app:
    build: . 
    container_name: laravel_app
    volumes:
      - ./laravel/src:/var/www
    networks:
      - komodo
    command: php-fpm -g 'daemon off;' 

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: orangit
      MYSQL_DATABASE: komodo
      MYSQL_USER: dewo
      MYSQL_PASSWORD: orangit
    volumes:
      - /var/lib/komodo/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

  nginx:
    build: 
      context: ./nginx  
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel/src:/var/www
    networks:
      - komodo
    depends_on:
      - app
      - phpmyadmin
volumes:
  mysql_data:

networks:
  komodo: