services:
  app:
    build: . 
    container_name: laravel_app
    volumes:
      - ./laravel/src:/var/www
    networks:
      - komodo
    command: php-fpm -g 'daemon off;' 

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - komodo

  nginx:
    build: 
      context: ./nginx  
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel/src:/var/www
    networks:
      - komodo
    depends_on:
      - app
      - mysql
volumes:
  mysql_data:

networks:
  komodo: